import type { Context } from "hono";
import type { Env } from "../types";

export async function handleInstall(c: Context<{ Bindings: Env }>): Promise<Response> {
  const script = generateInstallScript(c.env.SERVER_URL);
  return c.text(script, 200, {
    "Content-Type": "text/plain; charset=utf-8",
    "Content-Disposition": 'inline; filename="install.sh"',
  });
}

// Shell vars use plain $VAR; only ${serverUrl}/${bar} are TS interpolations.
function generateInstallScript(serverUrl: string): string {
  // The long-running agent binary. Heartbeats the server on an interval.
  const agentLines = [
    "#!/bin/sh",
    'CONF="${XDG_CONFIG_HOME:-$HOME/.config}/statch/agent.conf"',
    '[ -f "$CONF" ] || { echo "Config not found: $CONF" >&2; exit 1; }',
    '. "$CONF"',
    "",
    'if [ "$1" = "--uninstall" ]; then',
    '  CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/statch"',
    '  AGENT_BIN="$HOME/.local/bin/statch-agent"',
    '  SERVICE_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user/statch-agent.service"',
    "  if command -v systemctl >/dev/null 2>&1; then",
    "    systemctl --user stop statch-agent 2>/dev/null || true",
    "    systemctl --user disable statch-agent 2>/dev/null || true",
    '    rm -f "$SERVICE_FILE"',
    "    systemctl --user daemon-reload 2>/dev/null || true",
    "  fi",
    "  crontab -l 2>/dev/null | grep -v statch-agent | crontab - 2>/dev/null || true",
    '  rm -f "$AGENT_BIN" "$CONF_DIR/agent.conf"',
    '  rmdir "$CONF_DIR" 2>/dev/null || true',
    '  echo "Statch agent uninstalled."',
    "  exit 0",
    "fi",
    "",
    ': "${SERVER_URL:?SERVER_URL not set in $CONF}"',
    ': "${AGENT_TOKEN:?AGENT_TOKEN not set in $CONF}"',
    ': "${INTERVAL:=30}"',
    "",
    "send_heartbeat() {",
    '  curl -sf -X POST "$SERVER_URL/api/heartbeat" \\',
    '    -H "Authorization: Bearer $AGENT_TOKEN" \\',
    '    -H "Content-Type: application/json" \\',
    "    -d '{}' > /dev/null 2>&1 || true",
    "}",
    "",
    "# --once: single heartbeat then exit (used by cron, one process per tick)",
    'if [ "$1" = "--once" ]; then',
    "  send_heartbeat",
    "  exit 0",
    "fi",
    "",
    "# default: long-running loop (used by the systemd service)",
    "while true; do",
    "  send_heartbeat",
    '  sleep "$INTERVAL"',
    "done",
  ].join("\n");

  const serviceFile = [
    "[Unit]",
    "Description=Statch Agent",
    "After=network-online.target",
    "Wants=network-online.target",
    "",
    "[Service]",
    "Type=simple",
    "ExecStart=%h/.local/bin/statch-agent",
    "Restart=always",
    "RestartSec=10",
    "",
    "[Install]",
    "WantedBy=default.target",
  ].join("\n");

  const bar = "─".repeat(38);

  const lines = [
    "#!/bin/sh",
    `# Statch Agent Installer — ${serverUrl}`,
    "# Usage: curl -fsSL " + serverUrl + "/install.sh | STATCH_TOKEN=<token> sh",
    "# No root required — installs to ~/.config and ~/.local/bin",
    "set -e",
    "",
    'SERVER_URL="' + serverUrl + '"',
    'CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/statch"',
    'CONF_FILE="$CONF_DIR/agent.conf"',
    'BIN_DIR="$HOME/.local/bin"',
    'AGENT_BIN="$BIN_DIR/statch-agent"',
    'SERVICE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"',
    'SERVICE_FILE="$SERVICE_DIR/statch-agent.service"',
    "",
    "# Colors — only when stdout is a real terminal",
    "if [ -t 1 ]; then",
    "  C_RESET=$(printf '\\033[0m');    C_BOLD=$(printf '\\033[1m');    C_DIM=$(printf '\\033[2m')",
    "  C_RED=$(printf '\\033[31m');     C_GREEN=$(printf '\\033[32m');  C_YELLOW=$(printf '\\033[33m')",
    "  C_BLUE=$(printf '\\033[34m');    C_MAGENTA=$(printf '\\033[35m');C_CYAN=$(printf '\\033[36m')",
    "else",
    "  C_RESET=; C_BOLD=; C_DIM=; C_RED=; C_GREEN=; C_YELLOW=; C_BLUE=; C_MAGENTA=; C_CYAN=",
    "fi",
    "",
    'step() { printf "%s➜%s %s\\n" "$C_BLUE$C_BOLD" "$C_RESET" "$1"; }',
    'ok()   { printf "%s✓%s %s\\n" "$C_GREEN$C_BOLD" "$C_RESET" "$1"; }',
    'die()  { printf "%s✗ %s%s\\n" "$C_RED$C_BOLD" "$1" "$C_RESET" >&2; exit 1; }',
    "",
    "# Banner",
    'printf "\\n%s  🛰️  Statch Agent%s %sinstaller%s\\n" "$C_MAGENTA$C_BOLD" "$C_RESET" "$C_DIM" "$C_RESET"',
    'printf "%s      %s%s\\n\\n" "$C_DIM" "$SERVER_URL" "$C_RESET"',
    "",
    'command -v curl >/dev/null 2>&1 || die "curl is required but not installed."',
    "",
    "write_agent_bin() {",
    '  mkdir -p "$BIN_DIR"',
    '  cat > "$AGENT_BIN" << \'AGENT_EOF\'',
    agentLines,
    "AGENT_EOF",
    '  chmod +x "$AGENT_BIN"',
    "}",
    "",
    "# Re-run: upgrade binary and restart whichever runner is in use",
    'if [ -f "$CONF_FILE" ]; then',
    '  step "Existing installation detected — upgrading agent..."',
    "  write_agent_bin",
    '  if command -v systemctl >/dev/null 2>&1 && systemctl --user is-active --quiet statch-agent 2>/dev/null; then',
    "    systemctl --user restart statch-agent",
    '    ok "Agent service restarted."',
    "  else",
    '    printf "%s   (cron agent picks up the new binary on its next run)%s\\n" "$C_DIM" "$C_RESET"',
    "  fi",
    '  ok "Upgrade complete. 🎉"',
    "  exit 0",
    "fi",
    "",
    "# Enrolment token comes from the environment: STATCH_TOKEN=... sh",
    'if [ -z "$STATCH_TOKEN" ]; then',
    '  die "STATCH_TOKEN not set. In the admin panel: Monitors → Add server → copy the one-line command."',
    "fi",
    "",
    'HOSTNAME_VAL=$(hostname 2>/dev/null || echo "unknown-host")',
    'step "Enrolling this machine as \'$HOSTNAME_VAL\'..."',
    'RESPONSE=$(curl -sf -X POST "$SERVER_URL/api/agents/enroll" \\',
    '  -H "Authorization: Bearer $STATCH_TOKEN" \\',
    '  -H "Content-Type: application/json" \\',
    '  -d "{\\"hostname\\":\\"$HOSTNAME_VAL\\"}") || die "Enrolment failed — token invalid/expired or $SERVER_URL unreachable."',
    "",
    "MONITOR_ID=$(printf '%s' \"$RESPONSE\" | grep '^MONITOR_ID=' | sed 's/^MONITOR_ID=//')",
    "AGENT_TOKEN=$(printf '%s' \"$RESPONSE\" | grep '^AGENT_TOKEN=' | sed 's/^AGENT_TOKEN=//')",
    "MON_NAME=$(printf '%s' \"$RESPONSE\" | grep '^NAME=' | sed 's/^NAME=//')",
    "",
    '[ -z "$AGENT_TOKEN" ] && die "Enrolment returned an unexpected response."',
    'ok "Enrolled."',
    "",
    'mkdir -p "$CONF_DIR"',
    'cat > "$CONF_FILE" << EOF',
    "MONITOR_ID=$MONITOR_ID",
    "AGENT_TOKEN=$AGENT_TOKEN",
    "SERVER_URL=" + serverUrl,
    "INTERVAL=30",
    "EOF",
    'chmod 600 "$CONF_FILE"',
    "",
    "write_agent_bin",
    "",
    "# Send one heartbeat right away so it flips to 'up' immediately",
    '"$AGENT_BIN" --once',
    "",
    `printf "\\n%s┌${bar}┐%s\\n" "$C_CYAN$C_BOLD" "$C_RESET"`,
    'printf "%s│%s  🎉 Monitor live: %s%-19s%s%s│%s\\n" "$C_CYAN$C_BOLD" "$C_RESET" "$C_GREEN$C_BOLD" "$MON_NAME" "$C_RESET" "$C_CYAN$C_BOLD" "$C_RESET"',
    `printf "%s└${bar}┘%s\\n\\n" "$C_CYAN$C_BOLD" "$C_RESET"`,
    "",
    "# Install as systemd user service (cron fallback)",
    "if command -v systemctl >/dev/null 2>&1 && systemctl --user status >/dev/null 2>&1; then",
    '  mkdir -p "$SERVICE_DIR"',
    '  cat > "$SERVICE_FILE" << \'SVC_EOF\'',
    serviceFile,
    "SVC_EOF",
    "  systemctl --user daemon-reload",
    "  systemctl --user enable statch-agent",
    "  systemctl --user start statch-agent",
    '  ok "Running as a systemd user service."',
    "else",
    '  LOG_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/statch"',
    '  mkdir -p "$LOG_DIR"',
    '  (crontab -l 2>/dev/null | grep -v statch-agent; echo "* * * * * $AGENT_BIN --once >> $LOG_DIR/agent.log 2>&1") | crontab -',
    '  ok "Running via cron (every minute)."',
    "fi",
    "",
    'printf "%sTo uninstall:%s %s%s --uninstall%s\\n" "$C_DIM" "$C_RESET" "$C_BOLD" "$AGENT_BIN" "$C_RESET"',
  ];

  return lines.join("\n") + "\n";
}
